### ISSUE TITLE
HiddenColumns property problem

### ISSUE THREAD

**Issue by zebt** [HalitTalha/mat-table-extensions#37] opened 2020-01-27 14:03 UTC
Hey,

I have a small problem with extension.

When, I set for instance `hiddenColumns="13"` it will actually hide columns with index 1 and 3, not 13.

**Comment by HalitTalha** [comment] 2020-01-28 05:29
`hiddenColumns `is an `Array`. Please make sure `hiddenColumns `is surrounded by [ ]
like so: 
`[hiddenColumns] = "[3,5,11]"`

Duplicate of  #1

**Closed by HalitTalha** 2020-01-28 05:29 UTC
Labels: duplicate, question
