### ISSUE TITLE
ÿþ characteres appear at the beggining of a text file

### ISSUE THREAD

**Issue by MarcoV1** [HalitTalha/mat-table-extensions#29] opened 2020-01-03 13:44 UTC
When you export a table in txt format (using mat-table-exporter), ÿþ appears. I haven't found anyone having this issue with this dependency, so I'm looking for help on how to solve this issue.

Regards

**Comment by HalitTalha** [comment] 2020-01-05 10:50
Thanks for reporting. This is a duplicate of #26

**Closed by HalitTalha** 2020-01-05 10:50 UTC
Labels: duplicate
